history_on_the_go/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tour_app.urls')),
    path('admin/', admin.site.urls),
]

tour_app/urls.py
from django.urls import include, path
from . import views

app_name = 'tour_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.mapPage, name='mapPage'),
    path('register/', views.registerPage, name='registerPage'),
    path('login/', views.loginPage, name='loginPage'),
    path('logout/', views.logout_request, name='logout'),
    path('profile/', views.profilePage, name="profile"),
    path('tests/map_test', views.map_test, name='map_test'),
    path('saveLocation/', views.saveLocation, name='saveLocation'),
]

tour_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Itinerary(models.Model):
    """A user's saved itinerary of locations 

    Attributes:
        - id (PRIMARY KEY)
        - itinerary_name (NOT NULL)
        - locations (need another table for locations)
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
    )
    itinerary_name = models.CharField(max_length=100)
    def __str__(self):
        return self.itinerary_name


class Itinerary_location(models.Model):
    """Holds the locations of a given itinerary 

    Attributes:
        - id (PRIMARY KEY)
        - itinerary_id
        - location_name (NOT NULL) 
        - latitude (REAL UNIQUE NOT NULL)
        - longitude (REAL UNIQUE NOT NULL)       
    """
    itinerary = models.ForeignKey(
        Itinerary, 
        on_delete=models.CASCADE, 
    )
    loc_name = models.CharField(max_length=100)
    latitude = models.DecimalField(max_digits=17, decimal_places=6)
    longitude = models.DecimalField(max_digits=18, decimal_places=6)
    def __str__(self):
        return self.loc_name


class Profile(models.Model):
    """Stores a user's information 

    Attributes:
        - id (PRIMARY KEY)
        - address (NOT NULL)
        - city (NOT NULL)
        - zipcode (NOT NULL)
        - zip_ext (nullable, can be blank)
    """
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=90, default="")
    zipcode = models.CharField(max_length=5, default="")


class HistoricalLocation(models.Model):
    """Stores information regarding a historically relevant location

    Attributes:
        - id (PRIMARY KEY)
        - location_name (NOT NULL)
        - location_address (NOT NULL)
        - latitude (REAL UNIQUE NOT NULL)
        - longitude (REAL UNIQUE NOT NULL)
        - description (TEXT)
        - operation_hours (TIME)
        - pictures (BLOB)

    Notes:
        - latitude ranges from -90 - 90
        - longitude ranges from -180 to 80
        - both can store up to 15 decimal numbers 
    """
    loc_name = models.CharField(max_length=100)
    loc_address = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=17, decimal_places=15, unique=True)
    longitude = models.DecimalField(max_digits=18, decimal_places=15, unique=True)
    description = models.TextField()
    operation_hours = models.TimeField()
    pictures = models.BinaryField() 

tour_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import widgets

from tour_app.models import Profile


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255, label="First Name",
                                 widget=forms.TextInput(attrs={
                                     "placeholder": "Enter First Name",
                                     "class": "form-input"}))
    last_name = forms.CharField(max_length=255, label="Last Name",
                                widget=forms.TextInput(attrs={
                                    "placeholder": "Enter Last Name",
                                    "class": "form-input"}))
    email = forms.EmailField(max_length=255, label="Email Address",
                             widget=forms.TextInput(attrs={
                                 "placeholder": "example@email.com",
                                 "class": "form-input"}))
    city = forms.CharField(max_length=255, label="City",
                           widget=forms.TextInput(attrs={
                               "placeholder": "Enter City",
                               "class": "form-input"}))
    address = forms.CharField(max_length=255, label="Home Address",
                              widget=forms.TextInput(attrs={
                                  "placeholder": "Enter Home Address",
                                  "class": "form-input"}))
    zipcode = forms.CharField(max_length=5, label="Zip Code",
                              widget=forms.TextInput(attrs={
                                  "placeholder": "00000",
                                  "class": "form-input"}))

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']


def form_validation_check(form) -> str:
    """If any error occurs in the form, return an error message

    param form: the form that is passed in
    returns: error message for the associated form field
    """
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field.label,
                                   'label') else 'Error', error)
    return msg

tour_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, response
from django.contrib.auth.decorators import login_required
from tour_app.models import Itinerary
from .forms import RegisterUserForm, ProfileForm, form_validation_check
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from tour_app.models import Itinerary, Itinerary_location
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.utils.datastructures import MultiValueDictKeyError

from .models import Profile

app_name = 'main'

# Create your views here.
def registerPage(request):
    regis_form = RegisterUserForm()
    context = {'regis_form': regis_form}
    # If I don't assign for var_password1 and var_password2, template would throw errors
    var_email = ""
    var_registering_username = ""
    var_password1 = ""
    var_password2 = ""
    if request.method == 'POST':
        regis_form = RegisterUserForm(request.POST)
        var_registering_username = request.POST['username']
        var_email = request.POST['email']
        var_password1 = request.POST['password1']
        var_password2 = request.POST['password2']

        print("var_email = ", var_email)
        try:
            if get_user_model().objects.get(username=var_registering_username):
                messages.error(request, "Username has been used")
                messages.info(request, "Notes: Invalid information would cause a redirection to this page")
                return render(request, 'tour_app/registration.html', context)
        except:
            print("Good for register")

        if regis_form.is_valid():
            emails = get_user_model().objects.all()
            if any(True for objectName in emails if var_email == objectName.email):
                messages.error(request, "Email has been used")
                messages.info(request, "Notes: Invalid information would cause a redirection to this page")
                return render(request, 'tour_app/registration.html', context)

            # for objectName in emails:
            #     print(objectName.email)
            #     if var_email == objectName.email:
            #         messages.error(request, "Email has been used")
            #         messages.info(request,
            #                       "Notes: User would be redirect to registration page if username has been used")
            #         return render(request, 'tour_app/registration.html', context)
            regis_form.save()
            var_username = request.POST['username']
            user = get_user_model().objects.get(username=var_username)
            new_itinerary = Itinerary(user_id=user.id, itinerary_name=(var_username + ' Itinerary'))
            new_itinerary.save()
            return HttpResponseRedirect(reverse('tour_app:loginPage'))

    if var_password1 == var_password2:
        print("Password Matched")
    else:
        messages.error(request, "Password is not matching")

    messages.info(request, "Notes: Invalid information would cause a redirection to this page")
    return render(request, 'tour_app/registration.html', context)


def loginPage(request):
    var_flag = False
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username == "":
            var_flag = True
            messages.error(request, "Please provide username")
        if password == "":
            var_flag = True
            messages.error(request, "Please provide password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('tour_app:mapPage'))
        else:
            if not var_flag:
                try:
                    if get_user_model().objects.get(username=username):
                        messages.error(request, "Incorrect Password")
                        return render(request, 'tour_app/login.html', context)
                except:
                    print("Cannot find reason")

                messages.error(request, "Cannot find username")
                return render(request, 'tour_app/login.html', context)

    return render(request, 'tour_app/login.html', context)


# user profile form page
@login_required(login_url=' tour_app/login/')
def profilePage(request):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect("/profile")
    else:
        form = ProfileForm(instance=request.user.profile)
    context = {'profile_form': form}
    return render(request, 'tour_app/profilePage.html', context)


def index(request):
    context = {
        "google_api_key": settings.GOOGLE_API_KEY}  # Retrieves the google api key from the setting.py file which in turn gets the key from the ..env file
    return render(request, 'tour_app/index.html', context)



def mapPage(request):
    if request.method == 'POST':
        context = {
            "figure": request.POST['figure'],
            "lat": request.POST['lat'],
            "lng": request.POST['lng'],
            "placeName": request.POST['placeName'],
            "radius": request.POST['radius'],
            "google_api_key": settings.GOOGLE_API_KEY
            }
    else:    
        context = {"google_api_key": settings.GOOGLE_API_KEY}  # Retrieves the google api key from the setting.py file which in turn gets the key from the ..env file
    
    return render(request, 'tour_app/mapPage.html', context)



def map_test(request):
    context = {
        "google_api_key": settings.GOOGLE_API_KEY}  # Retrieves the google api key from the setting.py file which in turn gets the key from the ..env file
    return render(request, 'tour_app/map_test.html', context)


def saveLocation(request):
    if request.method == 'POST' and request.user.is_authenticated:
        user = request.user.username
        Itinerary_obj = Itinerary.objects.get(itinerary_name=user + " Itinerary")

        location_name = request.POST['place_name']
        lat = request.POST['lat']
        long = request.POST['lng']
        location = Itinerary_location(loc_name=location_name, latitude=lat, longitude=long,
                                      itinerary_id=Itinerary_obj.id)
        location.save()
        response = JsonResponse({"message": "Location added to Itinerary"})
        response.status_code = 201
        return response  # Sending an success response
    else:
        response = JsonResponse({"message": "Can not save location to initnerary, user not logged in."})
        response.status_code = 403  
        return response

def logout_request(request):
    logout(request)
    messages.info(request, "You have logged out")
    return redirect("tour_app:mapPage")

tour_app/templates/tour_app/index.html
<!DOCTYPE html>

<!-- These are the headers for the html file-->
<html lang="en">
    <head>
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>History on the Go</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- <link rel="preconnect" href="https://fonts.gstatic.com"> -->
        <link href="https://fonts.googleapis.com/css2?family=Amiko:wght@400;600;700&display=swap" rel="stylesheet">
        <!-- Core theme CSS (includes Bootstrap)-->



    <!-- This is where we load the css from bootstrap.-->
        {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'tour_app/landingPage.css' %}">
    

    <!-- This code is for the top bar, in order to navigate to the index page, login page, and register page,.-->
      
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="index.html">  </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href={% url 'tour_app:index' %} style='text-transform: None !important; font-weight: 600;'>Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href={% url 'tour_app:loginPage' %} style='text-transform: None !important; font-weight: 600;'>Login</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href={% url 'tour_app:registerPage' %} style='text-transform: None !important; font-weight: 600;'>Register</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header style='padding-bottom: 0;' class="masthead">
            <div class="container">
                <div class='row'>
                    <div style='align-self: center; align-content: flex-start;' class="col-md-6">
                        <div id='mainTitle' class="masthead-heading" style='margin-bottom: 26px;'>History On The Go</div>
                        <div id='subtitle' style='width: 70%; margin-bottom: 26px; ' class="masthead-subheading" >For countless adventures straight from your phone.</div>
                        <a id='signupBtn' style=' text-transform: None !important; padding: 0.55rem 2.75rem; flex: None; align-self: flex-start; float: left; background-color: #FF4B2B;' class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href='{% url 'tour_app:mapPage' %}'>Try it out!</a>

                    </div>
                    <div class="col-md-6" >
                        <img style='width: 50%;' src="{% static 'tour_app/images/iphone-mockup.png' %}"alt="mvp product" />
                    </div>
                </div>
            </div>
        </header>
        <!-- Description on how the app works. -->
        <section class="page-section" id="services">
            <div class="container">


                <div class="text-center">
                    <h3 style='margin-bottom: 50px;' class="section-heading ">How History On The Go Works Explaination</h3>
                </div>


               <div class="row text-center">
                    <div class="col-md-4">
                     
                        <h4 class="my-3 color-black-txt">1. Enter a Historical <br> figure   </h4>
                        <input id="map-input-Figure" type="text" placeholder="Historical Figures"/>
                    </div>
                    <div class="col-md-4">
                        <h4 class="my-3 color-black-txt">2. Enter an address to search for nearby historical locations</h4>
                        <input id="map-input-address" type="text" placeholder="Historical Places" />
                    </div>


                    <div class="col-md-4">
                        <h4 class="my-3 color-black-txt">3. Select a Radius(km) for your address</h4>

                                      <select id="map-input-radius" class="form-control" name="radius">
                                        <option class="map-input-option" value="5">5</option>
                                        <option class="map-input-option" value="10">10</option>
                                        <option class="map-input-option" value="25">25</option>
                                        <option class="map-input-option" value="50">50</option>
                                        <option class="map-input-option" value="100">100</option>
                                      </select>
                              
                    </div>
                </div>



                <div class="container">
                  <div class="text-center">


                    <button  id="submitbutton" class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" style='margin-top: 4.5rem; background-color: #FF4B2B;'> Search Here!  </button>
                    

            </div>
        </section>
        <!-- Contact us, this is for users who want to join the app.-->
        <section class="page-section" style ='background-color: #f3e0e2;' id="contact">
            <div class="container">
                <div class="text-center">
                    <h3 class="section-heading" style='margin-bottom: 2.5rem;'>Join Us</h3>
                    <h3 class="section-subheading text-muted" style='margin-bottom: 2.5rem;'>We are launching soon. Be one of the first to join History On The Go.</h3>
                    <a id='signupBtn' style=' text-transform: None !important; padding: 0.55rem 2.75rem; flex: None; align-self: flex-start; float: center; background-color: #FF4B2B;' class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href='{% url 'tour_app:registerPage' %}'>Register Here!</a>
                </div>
            </div>
        </section>
        <!-- Footer for social networks, facebook, twitter-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">  </div>
                    
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="mr-3" href={% url 'tour_app:index' %}>Home</a>
                        <a class="mr-3" href="{% url 'tour_app:loginPage' %}">Login</a>
                        <a href="{% url 'tour_app:registerPage' %}">Register</a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <!-- <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a> -->
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
                <p style='margin:0; padding:0; font-size: 0.7rem; color: #B2B2B2;'>Copyright History On The Go Co. 2021</p>
            </div>



        </footer>


        </div>

        <!-- Javascript to make the "How History On The Go" search bar work. -->
        <script
        src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&libraries=places&v=weekly"
        ></script>
        {% load static %}
        <div id="mapPageUrl" style="display:none"> {% url 'tour_app:mapPage' %}</div>
        <script src="{% static "tour_app/index.js" %}"></script> 
        <script type="text/javascript">init();</script>

    </body>
</html>

tour_app/templates/tour_app/login.html
<!DOCTYPE html>
<html>
<!-- These are the headers for what the title of this login page will be and what the code should reference-->
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login Page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tour_app/login.css' %}">
</head>
<body>
<div class="container" id="container">
    <div class="form-container log-in-container">

        <!-- This is for the form that the user submits to login, will need to link with our database -->
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Login</h1>
            <!-- This contains the section for the social media logins, facebook and twitter -->
            <div class="social-container">
                <a href="https://www.facebook.com/" class="social"><i class="fa fa-facebook fa-2x"></i></a>
                <a href="https://twitter.com/" class="social"><i class="fab fa fa-twitter fa-2x"></i></a>
            </div>
            <span>or use your account</span>
            <input type="text" name="username" placeholder="Username"/>
            <input type="password" name="password" placeholder="Password"/>
            <ul class="messages">
                {% for message in messages %}
                <li
                        {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            <a href="#">Forgot your password?</a>
            <button>Log In</button>
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-right">
                <h1>History on the Go</h1>
                <!-- This button once clicked directs you to the register page-->
                <button2 onClick="window.location.href={% url 'tour_app:registerPage' %};">
                    Register Here
                </button2>
            </div>
        </div>
    </div>
</div>
</body>
</html>

tour_app/templates/tour_app/mapPage.html
<!DOCTYPE html>
<html>
  <head>

    <title>History on the Go</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tour_app/mapStyle.css' %}">
  </head>
  <body class="container-fluid">
    <div id="start-location-marker" style="display:none"> {% static 'tour_app/images/map_home.png' %}</div>
    <div id="mainRow" class="row overflow-hidden">

      <!--displays google maps-->
      <div id="mapContainer" class="col-lg"> 
        <div id="map"></div>
      </div>
      <!--Search Results sidebar-->
      <div id="sidebar_col" class="col-lg-2">
        <div id="sidebar" class="">
          {% comment %}Profile button and login logout{% endcomment %}
          <div class="row">
            <div class="col">
            {% if user.is_authenticated %}
              <a href="{% url 'tour_app:profile' %}" class="btn btn-info">Profile</a>
              <a href="{% url 'tour_app:logout' %}" class="btn btn-warning">Logout</a>
            {% else %}
              <a href="{% url 'tour_app:loginPage' %}" class="btn btn-info">Login</a>
              <a href="{% url 'tour_app:registerPage' %}" class="btn btn-warning">Register</a>  
            {% endif %}
            </div>
          </div>
          <!--Search box-->
          <div id ="input_container">
            <label class ="form-label" for="Figure">Enter a Historical Figure:</label>
            <input id="map-input-Figure" name="Figure" class="form-control" type="text" placeholder="Enter Historical Figure"/>
            <label class ="form-label" for="address">Enter Address to Search from: </label>
            <input id="map-input-address" name="address" class="form-control controls" type="text" placeholder="Enter Search Address"/>
            {% comment %} <span id="profile"><button id="profile-btn">Profile</button></span> {% endcomment %}
            <div>
              <label class ="form-label" for="radius">Search Radius (km): </label>
              <select id="map-input-radius" class="form-control" name="radius">
                <option class="map-input-option" value="5">5</option>
                <option class="map-input-option" value="10">10</option>
                <option class="map-input-option" value="25">25</option>
                <option class="map-input-option" value="50">50</option>
                <option class="map-input-option" value="100">100</option>
              </select>
            </div>
            <input id="searchSubmitButton" class="form-control btn btn-primary mb-3" type="button" value="Search Based on Historical Figure">
          </div>
            <ul id="sidebar-tablist" class="nav nav-tabs" role="tablist">
              <li class="nav-item" role="presentation">
                <button id="results-tab" class="nav-link active" data-bs-toggle="tab" data-bs-target="#places" type="button" role="tab" aria-controls="places" aria-selected="true">Results</button>
              </li>
              <li class="nav-item" role="presentation">
                <button id="directions-tab" class="nav-link" data-bs-toggle="tab" data-bs-target="#directions" type="button" role="tab" aria-controls="directions" aria-selected="false">Directions</button>
              </li>
            </ul>
            <div class="tab-content" id="sidebarContent">
              {% csrf_token %}
              <div id="places" class="tab-pane fade show active places_list" role="tabpanel" aria-labelledby="results-tab"></div>
              <div id="directions" class="tab-pane fade" role="tabpanel" aria-labelledby="directions-tab"></div>
            </div>  
        </div>
      </div>

    </div>

    {% load static %}
    <!--Loads google map api-->
    <script
      src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&libraries=places&v=weekly"
      
    ></script>
    <script src="{% static "tour_app/google_map.js" %}"></script>
    <script>initMap(); </script> 
    <script type="text/javascript">
      {% if lat and lng %}
        var figure = "{{figure|safe}}";
        var lat = "{{lat|safe}}";
        var lng = "{{lng|safe}}";
        var placeName  = "{{placeName|safe}}";
        var radius = "{{radius|safe}}";
        $('#map-input-Figure').val(figure);
        $('#map-input-address').val(placeName);
        searchRequestFromPost(lat,lng,figure,radius);
      {% endif %}
    </script>
  </body>

tour_app/templates/tour_app/profilePage.html
{% comment %}
TODO List:
- Make a sidebar for navigation
-
-
{% endcomment %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'tour_app/profile.css' %}">
</head>

<body>
  <h1>Profile Page</h1>
  {% comment %}Navigation button back to main content{% endcomment %}
  <a href="{% url 'tour_app:mapPage' %}" class="nav-btn">Back to Map Page</a>

  {% comment %}Profile update user information form{% endcomment %}
  <div class="content">
    <div class="form-container" id="update-user-info">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="subheader">User Information</h2>
        {% for field in profile_form %}
          <label class="form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
          {{ field }}
        {% endfor %}
        <div>
          <input type="submit" class="submit-btn" value="Update">
        </div>
      </form>
    </div>
  </div>

  {% comment %}Change password form{% endcomment %}
  <div class="content">  
    <div class="form-container" id="update-password">
      <h2 class="subheader">Change Password</h2>
      <form action="" method="POST">
        {% csrf_token %}
        <label class="form-label" for="current_password">Current Password</label>
        <input class="form-input" name="current_password" required>
        <label class="form-label" for="new_password">New Password</label>
        <input class="form-input" name="new_password" required>
        <label class="form-label" for="verify_password">Verify Password</label>
        <input class="form-input" name="verify_password">
        <div>
          <button type="submit" class="submit-btn">Update Password</button>
        </div>
      </form>
    </div>
  </div>

</body>
</html>